name: Build Ubuntu

on:
  pull_request:
    branches: [dev]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v6
      - name: setup python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"
          cache: "pip"
          cache-dependency-path: "**/requirements-build.txt"
      - run: pip install -r requirements-build.txt
      - name: build via pyinstaller
        run: |
          rm -rf build dist
          pyinstaller --clean wthr.spec
          echo "✅ Готово! Исполняемый файл находится в папке dist/"
      - name: build via shiv
        run: |
          rm -f dist/wthr.pyz
          mkdir -p dist
          shiv . \
            --output-file dist/wthr.pyz \
            --entry-point "wthr.main:app" \
            --python "/usr/bin/env python3"
          echo "✅ Готово! Архив .pyz находится в папке dist/"
      - name: upload artifact linux
        uses: actions/upload-artifact@v6
        with:
          name: wthr-linux
          path: dist/wthr
      - name: upload artifact linux pyz
        uses: actions/upload-artifact@v6
        with:
          name: wthr-linux-pyz
          path: dist/wthr.pyz
